parameters:
    pm.googleauthenticator.class: PM\Bundle\GoogleAuthenticatorBundle\Services\GoogleAuthenticatorService

services:
    pm.googleauthenticator:
        class: '%pm.googleauthenticator.class%'
        public: true

